name: Compilar Bloxstrap Windows
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Baixar Código
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Configurar .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Compilar (Publish)
      run: |
        dotnet publish Bloxstrap/Bloxstrap.csproj -c Release -r win-x64 --self-contained -p:PublishSingleFile=true -o ./compilado
    - name: Upload do Executável
      uses: actions/upload-artifact@v4
      with:
        name: Bloxstrap-Compilado
        path: ./compilado/Bloxstrap.exe
